// src/redux/actions/types.js

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST'
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS'
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL'

export const USER_SEND_OTP_REQUEST = 'USER_SEND_OTP_REQUEST'
export const USER_SEND_OTP_SUCCESS = 'USER_SEND_OTP_SUCCESS'
export const USER_SEND_OTP_FAIL = 'USER_SEND_OTP_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_FORGOT_SEND_OTP_REQUEST = 'USER_FORGOT_SEND_OTP_REQUEST'
export const USER_FORGOT_SEND_OTP_SUCCESS = 'USER_FORGOT_SEND_OTP_SUCCESS'
export const USER_FORGOT_SEND_OTP_FAIL = 'USER_FORGOT_SEND_OTP_FAIL'

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST'
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS'
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL'
